language: java
jdk:
  - openjdk8

install: true

script: mvn install

branches:
 only:
    - master

after_success:
  - mvn coveralls:report

notifications:
  slack: cheese-dev:JXKSTVY4wHsMPbJi2uoKtyxs